"""领域模型、端口和纯业务规则。"""

from .account_consistency import (
    AccountConsistencyError,
    AccountConsistencyGuard,
    AccountConsistencyStatus,
    AccountProof,
    AccountProofProvider,
    AccountProofState,
    OneTimeAccountChallenge,
    ReadAccountScope,
)
from .browser_diagnostics import (
    sanitize_browser_page_diagnostics,
    sanitize_browser_task_message,
    sanitize_browser_task_result,
    sanitize_stored_browser_task,
)
from .browser_failure_diagnostics import missing_browser_failure_diagnostics
from .browser_ports import BrowserTaskExecutor
from .browser_runtime_telemetry import (
    mark_browser_runtime_telemetry_submitted,
    sanitize_browser_runtime_telemetry,
)
from .browser_sessions import BrowserCookieDeletionResult, LoginQrCodeResult
from .browser_tasks import (
    EPHEMERAL_XSEC_READ_KINDS,
    XSEC_TOKEN_TASK_KINDS,
    BrowserDriver,
    BrowserTask,
    BrowserTaskClaim,
    BrowserTaskExecutionResult,
    BrowserTaskKind,
    BrowserTaskStatus,
    browser_driver_supports,
    browser_task_may_write_platform,
    can_retry_browser_task,
)
from .capability_routing import (
    ProviderError,
    ProviderFailure,
    ProviderFailureCode,
    ProviderKind,
    RoutedCapabilityResult,
    RoutePolicyError,
    RouteStrategy,
)
from .collection import (
    CollectionBoard,
    CollectionDiff,
    CollectionFeedAccessContext,
    CollectionImportCommand,
    CollectionImportItem,
    CollectionSnapshot,
    CollectionSnapshotItem,
    CollectionStatus,
    collection_fingerprint,
)
from .collection_enrichment import (
    ENRICHMENT_VERSION,
    TERMINAL_ENRICHMENT_STATUSES,
    CollectionEnrichmentStatus,
    CollectionFeedDetail,
    CollectionFeedEnrichment,
)
from .collection_enrichment_ports import (
    CollectionEnrichmentRepository,
    EnrichmentStateConflictError,
)
from .collection_media import (
    CollectionMediaBatchRecord,
    CollectionMediaBatchStatus,
    CollectionMediaDeferredRecord,
    CollectionMediaItemRecord,
    CollectionMediaItemStatus,
)
from .collection_media_ports import CollectionMediaArtifactRepository
from .collection_ports import CollectionIdempotencyConflictError, CollectionRepository
from .errors import (
    BrowserTaskError,
    BrowserTaskLeaseConflictError,
    DownloadError,
    InvalidLinkError,
    InvalidPartialContentError,
    ManagedBrowserError,
    ParseError,
    PublicationError,
    SettingsError,
    TaskStateError,
    XhsError,
)
from .extension_identity import (
    build_extension_identity,
    split_extension_identity,
)
from .extension_presence import ExtensionPresence
from .feeds import (
    BrowserAccount,
    FeedAuthor,
    FeedComment,
    FeedDetailResult,
    FeedListResult,
    FeedMediaResource,
    FeedMediaResult,
    FeedMetrics,
    FeedSummary,
    ProfileMetric,
    UserProfileResult,
)
from .managed_browser import ManagedBrowserState, ManagedBrowserStatus
from .managed_publication import (
    ManagedPublicationExecutor,
    ManagedPublicationOutcome,
    ManagedPublicationProgress,
    ManagedPublicationProgressReporter,
)
from .models import (
    Author,
    ClientDownloadRecord,
    ClientRecordStatus,
    DownloadArtifact,
    DownloadMode,
    DownloadOutcome,
    DownloadRecord,
    DownloadTask,
    DownloadTaskStatus,
    MediaKind,
    MediaResource,
    WorkDetail,
    WorkType,
)
from .note_extraction import (  # noqa: F401
    ExtractionArtifact,
    ExtractionMediaType,
    ImageOcrRecord,
    NoteExtractionRecord,
    NoteExtractionStatus,
    TextProvenance,
    TextProvenanceSource,
)
from .note_extraction_ports import (  # noqa: F401
    AudioExtractor,
    ImageOcr,
    NoteExtractionRepository,
)
from .publication import (
    PublicationAsset,
    PublicationClaim,
    PublicationDraft,
    PublicationMode,
    PublicationTask,
    PublicationTaskStatus,
    PublicationVisibility,
)
from .video_content import (
    CollectionVideoContent,
    VideoArtifact,
    VideoOcrFrame,
    VideoOcrResult,
    VideoProcessingStatus,
    VideoStageStatus,
    VideoTranscript,
    VideoTranscriptSegment,
    overall_video_status,
)
from .video_ports import (
    VideoArtifactStore,
    VideoContentRepository,
    VideoInspector,
    VideoMediaAcquirer,
    VideoOcr,
    VideoStateConflictError,
    VideoTranscriber,
)

__all__ = [
    "ENRICHMENT_VERSION",
    "EPHEMERAL_XSEC_READ_KINDS",
    "TERMINAL_ENRICHMENT_STATUSES",
    "XSEC_TOKEN_TASK_KINDS",
    "AccountConsistencyError",
    "AccountConsistencyGuard",
    "AccountConsistencyStatus",
    "AccountProof",
    "AccountProofProvider",
    "AccountProofState",
    "Author",
    "BrowserAccount",
    "BrowserCookieDeletionResult",
    "BrowserDriver",
    "BrowserTask",
    "BrowserTaskClaim",
    "BrowserTaskError",
    "BrowserTaskExecutionResult",
    "BrowserTaskExecutor",
    "BrowserTaskKind",
    "BrowserTaskLeaseConflictError",
    "BrowserTaskStatus",
    "ClientDownloadRecord",
    "ClientRecordStatus",
    "CollectionBoard",
    "CollectionDiff",
    "CollectionEnrichmentRepository",
    "CollectionEnrichmentStatus",
    "CollectionFeedAccessContext",
    "CollectionFeedDetail",
    "CollectionFeedEnrichment",
    "CollectionIdempotencyConflictError",
    "CollectionImportCommand",
    "CollectionImportItem",
    "CollectionMediaArtifactRepository",
    "CollectionMediaBatchRecord",
    "CollectionMediaBatchStatus",
    "CollectionMediaDeferredRecord",
    "CollectionMediaItemRecord",
    "CollectionMediaItemStatus",
    "CollectionRepository",
    "CollectionSnapshot",
    "CollectionSnapshotItem",
    "CollectionStatus",
    "CollectionVideoContent",
    "DownloadArtifact",
    "DownloadError",
    "DownloadMode",
    "DownloadOutcome",
    "DownloadRecord",
    "DownloadTask",
    "DownloadTaskStatus",
    "EnrichmentStateConflictError",
    "ExtensionPresence",
    "FeedAuthor",
    "FeedComment",
    "FeedDetailResult",
    "FeedListResult",
    "FeedMediaResource",
    "FeedMediaResult",
    "FeedMetrics",
    "FeedSummary",
    "InvalidLinkError",
    "InvalidPartialContentError",
    "LoginQrCodeResult",
    "ManagedBrowserError",
    "ManagedBrowserState",
    "ManagedBrowserStatus",
    "ManagedPublicationExecutor",
    "ManagedPublicationOutcome",
    "ManagedPublicationProgress",
    "ManagedPublicationProgressReporter",
    "MediaKind",
    "MediaResource",
    "OneTimeAccountChallenge",
    "ParseError",
    "ProfileMetric",
    "ProviderError",
    "ProviderFailure",
    "ProviderFailureCode",
    "ProviderKind",
    "PublicationAsset",
    "PublicationClaim",
    "PublicationDraft",
    "PublicationError",
    "PublicationMode",
    "PublicationTask",
    "PublicationTaskStatus",
    "PublicationVisibility",
    "ReadAccountScope",
    "RoutePolicyError",
    "RouteStrategy",
    "RoutedCapabilityResult",
    "SettingsError",
    "TaskStateError",
    "UserProfileResult",
    "VideoArtifact",
    "VideoArtifactStore",
    "VideoContentRepository",
    "VideoInspector",
    "VideoMediaAcquirer",
    "VideoOcr",
    "VideoOcrFrame",
    "VideoOcrResult",
    "VideoProcessingStatus",
    "VideoStageStatus",
    "VideoStateConflictError",
    "VideoTranscriber",
    "VideoTranscript",
    "VideoTranscriptSegment",
    "WorkDetail",
    "WorkType",
    "XhsError",
    "browser_driver_supports", "browser_task_may_write_platform",
    "build_extension_identity", "can_retry_browser_task",
    "collection_fingerprint", "mark_browser_runtime_telemetry_submitted",
    "missing_browser_failure_diagnostics",
    "overall_video_status",
    "sanitize_browser_page_diagnostics",
    "sanitize_browser_runtime_telemetry",
    "sanitize_browser_task_message",
    "sanitize_browser_task_result", "sanitize_stored_browser_task",
    "split_extension_identity",
]
